### PR TITLE
Move CSS to SCSS and remove inline CSS method

### LINKED ISSUE #893: Feature Request: Move CSS to SCSS and remove inline CSS method
### Describe the feature

Currently we put the css in components. This has great advantages but the way we use pages and components ends up in bloated CSS being rendered to the DOM.

I suggest, but happy to be challenged and close this ticket, to move everything into a set of SCSS files that is built seperately or an alternative modern way.

https://nextjs.org/docs/basic-features/built-in-css-support#sass-support

### Advantages

Reduces page size
Reduces duplication of CSS

#### Acceptance Criteria

All CSS is removed from the React components
Site looks exactly the same

- [ ]

### PR DESCRIPTION
**Pull request by johnnolan**
### Description of the Change

Currently we put the css in components. This has great advantages but the way we use pages and components ends up in bloated CSS being rendered to the DOM.

https://nextjs.org/docs/basic-features/built-in-css-support#sass-support

@wordshaker this PR completely replaces the inline css with SCSS. Should make it much easier to create new content without duplicates everywhere.

The main things to pay attention to are

## Content sections must have a class set

You will see that all sections in pages have a new class `content-section`. This must be set on each for now to align content to the center.

`<section className="content-section">`

## SCSS in styles directory

I have tried on this first pass to not duplicate styles and where things are more component based, named and moved the styles to relevantly named files.

With any outstanding PRs, you will need to ensure any new styles are added to the SCSS files, otherwise you can build the pages using the same classes as others without issue.

### Things to PR

Look to see if you can spot any changes in style as you look through the site. I have been through three times but there may be the odd thing I haven't picked up on.

### Benefits

Reduces page size
Reduces duplication of CSS

### Applicable Issues

Fixes #893

### CODE REVIEW

**Comment by johnnolan** [comment]
@wordshaker Once all other PRs are in including your content changes I will work on this. Will need a manual click through and comapre for any broken styles once ready but should make creating content much easier in the future and changing styles globally.

**Comment by wordshaker** [comment]
Sorry I've been slow. I will test this soon

**Comment by johnnolan** [comment]
@wordshaker will take a look at this tonight/tomorrow night and push any fixes needed

**Comment by wordshaker** [comment]
Gonna merge it. Do you think we should add any of the detail from your description to the readme so people know how to work with the repo? Just a thought. Thanks for the excellent work

**Review by wordshaker — APPROVED** [review]

**Pull request merged**
