### PR TITLE
Speaker grid component and content

### PR DESCRIPTION
**Pull request by astannard**
### Description of the Change

Speaker grid now has a speaker component, I've added the talk title in too which is used within the component. This is better for the delegates.

### Benefits

Less code duplication, my pic is also included ;)

### CODE REVIEW

**Comment by wordshaker** [comment]
Looks like prettier needs to be run against this `npm run prettier:fix`

**Comment by wordshaker** [comment]
Looks great locally 😄 Thanks for this change 

image

Do you want it merged after Oct 1st so you get the hacktober credit?

**Comment by astannard** [comment]
Hi @wordshaker , Glad you like it!  May as well merge it now then I could update some of the other pages to use the new component for Hacktoberfest ? I've run the prettier again now

**Comment by wordshaker** [comment]
I can fix the ES Lint failures from the build if it helps :) and then I'll merge it

**Review by wordshaker — APPROVED** [review]

**Comment by wordshaker** [comment]
Thank you @astannard!

**Pull request merged**
