### PR TITLE
Add pa11y-ci

### LINKED ISSUE #970: Bug: Fix Pa11y Timeout Error
### Describe the bug

Fix Pa11y timeout issues and re-enable in the test and build workflow

**To Reproduce**

Steps to reproduce the behaviour:

1. Add the following to the test workflow

```
- name: Run pa11y
        run: npm run pa11y
```

2. Run test and build workflow

**Reproduces how often:**

100% of the time

**Expected behaviour**

Pally runs and does not timeout

**Screenshots**

image

### PR DESCRIPTION
**Pull request by johnnolan**
### Description of the Change

- Replaces pa11y with pa11y-ci for better integration with local and CI pipelines.
- Enables caching for node_modules properly increasing speed of pipeline builds.
- Adds axe fixes throughout
-  Bump next from 13.1.2 to 13.1.3

### Benefits

Uses a better method of running tests without the issues with directly using pa11y.

Currently does not run on windows terminal locally for some reason so testing in the pipeline.

### Applicable Issues

Fixes #970
Fixes #1014

### CODE REVIEW

**Comment by johnnolan** [comment]
Well that works which is good, will look at the errors another day and leave this here until happy

**Comment by johnnolan** [comment]
More axe fixes to come...

**Comment by johnnolan** [comment]
@wordshaker this PR brings in pa11y-ci to handle the accessibility checks properly. And finally I have got around to fixing all the issues it raised. It is mostly missing `<ul>` tags and a few contrast colour changes.

**Comment by wordshaker** [comment]
I'll give this a kicking and check over at the weekend before merging ❤️

**Comment by wordshaker** [comment]
There are a couple of front-end bits I want to fix before merging which I'll do at the weekend

**Review by wordshaker — APPROVED** [review]

**Comment by wordshaker** [comment]
Thanks for your work @johnnolan

**Pull request merged**
