### PR TITLE
Refactor companies component

### PR DESCRIPTION
**Pull request by johnnolan**
### Description of the Change

Refactors the companies component to use Hooks and Context.

### Benefits

This gives a more standard and modern way of managing state within a component and applies best practices to it

### CODE REVIEW

**Comment by johnnolan** [comment]
Needs tests written around it, naughty! You should have done that first man, jeez!

**Review by wordshaker — APPROVED** [review]

**Comment by wordshaker** [comment]
@johnnolan ...
image

**Review by wordshaker — CHANGES_REQUESTED** [review]
tests do not pass locally

**Review by wordshaker — APPROVED** [review]
Sorry, I'm and idiot

image

**Pull request merged**
