### PR TITLE
b/ Fixed the past photos link and added a test

### PR DESCRIPTION
**Pull request by carolgilabert**
### Requirements

✅ Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
✅ All new code requires tests to ensure against regressions

### Description of the Change

I was looking for last year's pics and noticed the link was broken, then I remembered the site is open source, so here's a PR 😇 

ℹ️ I looked for the Contributing page in the root of the repo but didn't check `.github` so I missed the present tense style guide, so my commit message is in past tense, sorry 🤦🏼‍♀️ 

### Benefits

The pictures page will be accessible through the main navigation.

### Applicable Issues

N/A

### CODE REVIEW

**Comment by wordshaker** [comment]
Sorry - just waiting for our actions to run

**Review by wordshaker — APPROVED** [review]

**Comment by wordshaker** [comment]
@carolgilabert can you run `npm run prettier:fix` on this and give it an extra push?

**Comment by carolgilabert** [comment]
@wordshaker yep, sure thing! Sorry, I thought VSCode/husky had handled it 😅

**Comment by wordshaker** [comment]
Thanks @carolgilabert!

**Pull request merged**
