### PR TITLE
Pa11y ci

### PR DESCRIPTION
**Pull request by johnnolan**
### Description of the Change

This PR add pa11y tests to the CI and locally. To run locally you can do `npm run pa11y` after you have run `npm run build && npm run export`

### Benefits

On PRs and merge to master you will get a check over all your outputted static HTML in the site.

### Applicable Issues

#172

### CODE REVIEW

**Comment by wordshaker** [comment]
any idea what the memory leak is about? Otherwise looks gooooood

image

**Comment by johnnolan** [comment]
> 
> 
> any idea what the memory leak is about? Otherwise looks gooooood
> 
> image

Ooh what is that tricky little devil, stand by, let me check the interwebs!

**Comment by johnnolan** [comment]
@wordshaker this should be good now for a final approval

**Comment by wordshaker** [comment]
Awesome sauce batman!

**Review by wordshaker — APPROVED** [review]

**Pull request merged**
