### PR TITLE
Updates to next 13 and fixes breaking changes

### PR DESCRIPTION
**Pull request by johnnolan**
### Description of the Change

Updates to the latest version of next (13) and fixes breaking changes from the update.

Also updates webpack and eslint.

### Benefits

Site working in newer version

### CODE REVIEW

**Review by wordshaker — APPROVED** [review]

**Comment by wordshaker** [comment]
I was just working on the same thing! You just beat me to it 😂

**Comment by wordshaker** [comment]
Awww boo. Pa11y is mad

**Comment by johnnolan** [comment]
Garrh! Reet, lets take a look 👀

**Comment by johnnolan** [comment]
Ran out of time tonight but initial findings are no visible changes have happened to the html output so maybe pa11y has just decided to start working properly recently? Not sure.

Will take another look tomorrow but two options right now.

1. Disable the required step for pa11y on the build in this PR and merge. Then do another ticket to work through the issues.
2. Fix the issues in this PR and merge.

@wordshaker  let me know which if any of those you want to do or whether you have another idea

**Comment by wordshaker** [comment]
Pa11y can be fixed by increasing `process.setMaxListeners(50);` to `process.setMaxListeners(100);`

once fixed though be careful to check all the images particularly the past speakers page. Need to fix images now layout is no longer a supported prop:
https://nextjs.org/docs/messages/next-image-upgrade-to-13

**Review by wordshaker — CHANGES_REQUESTED** [review]
Pa11y can be fixed by increasing process.setMaxListeners(50); to process.setMaxListeners(100);

once fixed though be careful to check all the images particularly the past speakers page. Need to fix images now layout is no longer a supported prop:
https://nextjs.org/docs/messages/next-image-upgrade-to-13

**Comment by johnnolan** [comment]
Images that are broken before merge

* /pastconferences/pastspeakers/pastspeakergrid/ images need style fixing
* /about-the-conference/ images need style fixing

**Comment by johnnolan** [comment]
I have gone through and updated links and images on the pages I can see errors with. Would be good if you could pull the branch and give it a once over in case I missed anything?

**Comment by johnnolan** [comment]
Issue with FontAwesome mock, will sort later today ⚰️

**Comment by johnnolan** [comment]
This should now be good to go 🚀 🙏

**Comment by wordshaker** [comment]
I'll give it a once over tomorrow. Pretty swamped at work today.

**Comment by wordshaker** [comment]
Sorry @johnnolan Can't merge it yet

image
image
image

I hope to get around to doing fixes this week but I'm a wee bit swamped atm

**Comment by wordshaker** [comment]
Also all the links to the speakers pages are broken on your branch
image

**Comment by johnnolan** [comment]
No problem at all, no rush on this! I will take a look tomorrow, seemed fine here so will delete my node_modules and do a fresh npm install locally in case that is the issue, thanks for checking!

**Comment by johnnolan** [comment]
Links fixed, must have been a change in the next link component. Also I nuked my package-lock.json and node_modules, did a fresh npm install and tested on FF and Chrome, all images working here. 

When you get time later in the week, it may be worth doing the same and trying again in case there is some old version in node hanging around. Take it easy and no rush!

**Review by wordshaker — APPROVED** [review]
Looks awesomesauce. Thanks for your hard work

**Pull request merged**
