### PR TITLE
Previous speaker use component

### PR DESCRIPTION
**Pull request by astannard**
I moved the new speaker component into the components updated speaker grid to use this and also the previous speakers page to use this component too

### Benefits

Reduce repeat code and be consistent across the speaker grid pages

### CODE REVIEW

**Comment by wordshaker** [comment]
@astannard looks like you still have a couple of conflicts to resolve

**Comment by astannard** [comment]
> @astannard looks like you still have a couple of conflicts to resolve

I might have to get some help on this tomorrow, I don't see the conflicts myself but I'm not use to using git with forked repos

**Comment by astannard** [comment]
> @astannard looks like you still have a couple of conflicts to resolve

That should be sorted now

**Review by pjgpetecodes — APPROVED** [review]
Looks good... Tha ms!

**Pull request merged**
