### PR TITLE
Edit next config

### PR DESCRIPTION
**Pull request by wordshaker**
### Requirements

- Fix routing in next config

### Benefits

Makes the site links work again

### Applicable Issues

N/A

### CODE REVIEW

**Comment by wordshaker** [comment]
@johnnolan what obvious mistake am I making here?

**Comment by johnnolan** [comment]
Quick glance you need to add back in the `out` directory and its contents https://github.com/DDDEastMidlandsLimited/dddem-web/commit/b829117074689feabaa40e8ef448b7e5f0b0df32#diff-633156f18bb308b0c675a947c272a319684a5ef64b8a2af971da794b7e23b36e

**Comment by wordshaker** [comment]
> Quick glance you need to add back in the `out` directory and its contents [b829117#diff-633156f18bb308b0c675a947c272a319684a5ef64b8a2af971da794b7e23b36e](https://github.com/DDDEastMidlandsLimited/dddem-web/commit/b829117074689feabaa40e8ef448b7e5f0b0df32#diff-633156f18bb308b0c675a947c272a319684a5ef64b8a2af971da794b7e23b36e)

Ok weird thing - I have that folder locally but it's not pushing up... I will investigate

**Comment by wordshaker** [comment]
When did that slip into the git ignore.... hmmmm

**Pull request merged**
