### PR TITLE
refactor: Added as many duplicate content areas as components

### PR DESCRIPTION
**Pull request by johnnolan**
### Description of the Change
Moves as many common content areas to components as I could find as requested in bug ticket #94 

Feel free to comment on any areas I may have missed and I can add them. A few were duplicated but had different content based on context of the page.

### Benefits

Reduces the size of the code base and potential for errors

### Applicable Issues

Issue #94

### CODE REVIEW

**Comment by wordshaker** [comment]
I'll give this a full dedicated review this week 👍

**Comment by johnnolan** [comment]
Thank @geekcubed feel free to dip into this as I may not get time until tomorrow to take a look anyway, otherwise I will sort that out!

**Comment by wordshaker** [comment]
As I saw this is still in progress I merged your other PR and left you with lots of tasty conflicts @johnnolan 😄

**Comment by wordshaker** [comment]
Sneaky one - can you fix the about link from the home page as well? Prettifier seems to have borked it. On initial click it goes to `https://www.dddeastmidlands.com/#`

**Comment by johnnolan** [comment]
> As I saw this is still in progress I merged your other PR and left you with lots of tasty conflicts @johnnolan 😄

haha, all sorted now and pushed!

**Pull request merged**
